name: Node dependencies compatibility

on:
  push:
  pull_request:
    branches: [master]
    types: [opened, edited]

jobs:
  buildAndTestAndLint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install ng cli
        run: npm install -g @angular/cli
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Check code style
        run: npm run lint
      # - name: Test
      #   run: npm run test